### ISSUE TITLE
Status of Blocking Socket Transport in Haigha

### ISSUE THREAD

**Issue by vitaly-krugl** [agoragames/haigha#70]
Hi @awestendorf: What is the status of Haigha with the Blocking Socket Transport? Is it stable and suitable for production deployment when used with Blocking Socket Transport?

Sorry for repeating the question that I emailed to you recently. I need to make an urgent decision with respect to AMQP client selection to solve a licensing incompatibility issue.

Best,
Vitaly

**Comment by awestendorf** [comment]
I don't use the blocking transport in production, but as far as I know it's in a good state.
