### ISSUE TITLE
Failed to parse timestamp in frame reader

### ISSUE THREAD

**Issue by lipixun** [agoragames/haigha#87]
The timestamp is 64bit in RabbitMQ timestamp, there will be an exception when trying to parse the timestamp by __datetime.utcfromtimestamp__

We have to divide the value by __1e6__ instead.

**Comment by vitaly-krugl** [comment]
I posted a question about this issue in https://groups.google.com/forum/#!topic/rabbitmq-users/_4ZRm8vX73g

**Comment by awestendorf** [comment]
Closing, see discussion in #88
